import { fmt, fmtDate } from '@/lib/invoice-helpers';

interface DocItem {
  description: string;
  quantity: number;
  unit_price_cents: number;
  total_cents: number;
}

interface PrintableDoc {
  kind: 'Quote' | 'Invoice';
  reference: string;
  clientName: string;
  status: string;
  dateLabel: string;
  dateValue: string | null;
  subtotal_cents: number;
  vat_cents: number;
  total_cents: number;
  notes: string | null;
  items: DocItem[];
}

/** Browser-print-based document: caller opens a popup, writes this HTML, then calls window.print(). */
export function printableBiztechDoc(doc: PrintableDoc): string {
  const rows = doc.items.map(i => `
    <tr>
      <td>${i.description}</td>
      <td style="text-align:right">${i.quantity}</td>
      <td style="text-align:right">${fmt(i.unit_price_cents)}</td>
      <td style="text-align:right">${fmt(i.total_cents)}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>${doc.kind} ${doc.reference}</title>
<style>
  * { box-sizing: border-box; }
  :root { color-scheme: light; }
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1a1a1a; background: #fff; margin: 0; }
  .header {
    background: linear-gradient(135deg, #31005E 0%, #5C3BCF 100%);
    color: #fff;
    padding: 32px 48px;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }
  .wordmark { font-size: 22px; font-weight: 800; letter-spacing: -0.02em; }
  .wordmark span { color: #DDC357; }
  .header-sub { font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; opacity: 0.75; margin-top: 2px; }
  .header-right { text-align: right; }
  .doc-kind { font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; opacity: 0.8; margin-bottom: 4px; }
  .doc-ref { font-size: 20px; font-weight: 700; font-family: monospace; }
  .body { padding: 32px 48px 48px; }
  .meta { display: flex; justify-content: space-between; margin-bottom: 28px; font-size: 13px; }
  .meta div { color: #555; }
  .meta strong { color: #1a1a1a; }
  .status-pill { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; background: rgba(92,59,207,0.1); color: #5C3BCF; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  th { text-align: left; font-size: 11px; text-transform: uppercase; color: #888; border-bottom: 2px solid #31005E; padding: 8px 4px; }
  td { font-size: 13px; padding: 10px 4px; border-bottom: 1px solid #eee; }
  .totals { margin-left: auto; width: 260px; font-size: 13px; }
  .totals div { display: flex; justify-content: space-between; padding: 4px 0; }
  .totals .total { font-weight: 700; font-size: 17px; color: #31005E; border-top: 2px solid #5C3BCF; margin-top: 6px; padding-top: 10px; }
  .notes { margin-top: 24px; font-size: 12px; color: #666; font-style: italic; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; font-size: 10px; color: #999; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="wordmark">MINT<span>BizTech</span></div>
      <div class="header-sub">Admin Portal</div>
    </div>
    <div class="header-right">
      <div class="doc-kind">${doc.kind}</div>
      <div class="doc-ref">${doc.reference}</div>
      <div class="status-pill" style="background: rgba(255,255,255,0.15); color: #fff;">${doc.status}</div>
    </div>
  </div>
  <div class="body">
    <div class="meta">
      <div><strong>Bill to</strong><br />${doc.clientName}</div>
      <div><strong>${doc.dateLabel}</strong><br />${fmtDate(doc.dateValue)}</div>
    </div>
    <table>
      <thead><tr><th>Description</th><th style="text-align:right">Qty</th><th style="text-align:right">Unit</th><th style="text-align:right">Total</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="totals">
      <div><span>Subtotal</span><span>${fmt(doc.subtotal_cents)}</span></div>
      <div><span>VAT (15%)</span><span>${fmt(doc.vat_cents)}</span></div>
      <div class="total"><span>Total</span><span>${fmt(doc.total_cents)}</span></div>
    </div>
    ${doc.notes ? `<p class="notes">${doc.notes}</p>` : ''}
    <div class="footer">MINT Platforms · Generated by MINT BizTech Admin Portal</div>
  </div>
</body>
</html>`;
}
